### ISSUE TITLE
Timing problem

### ISSUE THREAD

**Issue by JoachimF** [estechnical/reflowOvenController#2]
Hi, 
I made your oven controler, but I have a timing problem, when I unplug the usb port, the time is about 10 times faster than the real time. I try to plug the usb only on a power it's like nothing is plugged, so I suppose the communication with the computer make this. 
Have you an idea about that?
Also I couldn't be able to use your TFT library, I don't know why, the sreen stay white.

Thanks for your help,

Joachim

**Comment by estechnical** [comment]
Hi Joachim,

Are you sure it's our code you are using? We don't use a TFT lcd or base any timing on communication. The code should run based on the value provided by Millis() so I suggest that you have a hardware issue. Please share the code you are using, I cannot help otherwise...

Many thanks,
Ed

**Comment by JoachimF** [comment]
Hi, I don't know why but I was on the 0xPIT reflow controller, and the issue is on yours !!! 
Thanks for your awnser.
